### ISSUE TITLE
picode网络的训练细节

### ISSUE THREAD

**Issue by hz1272803128** [Bo396543018/Picodet_Pytorch#1]
**Describe the feature**
我也在复现picodet的网络，但是loss在训练集快速降到很小，但是验证集上的loss却比较大，map很低，由于是从paddlepaddle中抽取的部分代码，可能在训练上存在问题，也可能代码还有细节没注意到，希望博主能分享下训练的具体过程。
顺便提一下，预训练模型能在百度云上也放一个不？感谢
**Motivation**
A clear and concise description of the motivation of the feature.
Ex1. It is inconvenient when [....].
Ex2. There is a recent paper [....], which is very helpful for [....].

**Related resources**
If there is an official code release or third-party implementations, please also provide the information here, which would be very helpful.

**Additional context**
If you would like to implement the feature and create a PR, please leave a comment here and that would be much appreciated.

**Comment by Bo396543018** [comment]
您好，我现在自己复现的精度暂时还差一些，只有30.1，权重我后面会上传一下
