### ISSUE TITLE
NanoDet精度能对齐吗？

### ISSUE THREAD

**Issue by Senwang98** [Bo396543018/Picodet_Pytorch#2]
@Bo396543018 
你好，我最近在mmdet2上面尝试对齐一下nanodet的精度，但是似乎数据增强那边有些出入，看你写的不知道有没有对齐精度呢？

**Comment by Bo396543018** [comment]
在0.5x 320上基本可以对齐官方训练的结果，416上会差大概0.5个点。具体细节我也没有去对，因为主要还是想复现picodet，不过目前仍然差一点

**Comment by Senwang98** [comment]
@Bo396543018 
可以的，我其实觉得那个数据增强的color部分，nanodet的亮度是0.2，我看源码里面是先除255的，所以亮度那部分应该是不是mmdet默认的32，好像是0.2 * 255，不过应该不至于对结果有很大的影响才是

**Comment by Bo396543018** [comment]
嗯，是的，nanodet的数据增强我大致观察了下在mmdet里都能找到相应的函数，但是细节我没有完全对齐，比如某些初始值的设定，可能会存在一定波动。

**Comment by Senwang98** [comment]
@Bo396543018 
我能问一下，你们esnet的权重以及picodet的权重是手动修改的吗，因为我并没有用过paddle的东西（doge
picodet的权重mmdet2加载的时候会报mismatch，但是结果看起来没啥问题，似乎像是手动修改过权重名一样的结果

**Comment by Bo396543018** [comment]
对的，esnet和picodet的权重是从官方提供的权重转换过来的，主要操作就是对齐一下命名

**Comment by Senwang98** [comment]
@Bo396543018 
1. 我看一下picodet-s-416的log文件，兄弟你里面的每个epoch iter是360，按照你8张3090（HIT真的豪），每张80个，不应该是180+的iter吗？
2. 另外，我看了一下paddle-picodet的log文件，它的cosine lr变化似乎跟mmdet不一样，train的时候不加pad=32，但是eval的时候加了eval也怪怪的。

**Comment by Bo396543018** [comment]
1. 我是按照官方用的卡的数量4卡训练的
2. 这个cosine lr也是我奇怪的地方，我看源码二者公式应该是一致的，但是ppdet官方print出来是符合的，mmdet log里的感觉对应不上，暂时还没发现问题在哪，pad这个我倒没有注意。
另外这个code里的EMA实现还略微有点不同，ppdet里是初始化为0，我这边暂时是初始化为模型权重，最新一版初始化到0能训练到30.3（也有可能是训练本身的波动。)

**Comment by Senwang98** [comment]
@Bo396543018 
Okay，谢谢老哥，后续我这边再细致的对一下模型这些细节，这些是直接从config发现。模型的gflops跟params暂时跟picodet对不上，我对齐完nanodet之后在你的基础上再对一下。

**Comment by Bo396543018** [comment]
嗯 好的，因为推理对齐了，gflops和params参数量我就没刻意对，刚看了下，确实有点差异，参数量可能受gfl_reg影响，flops暂时不明确

**Comment by Senwang98** [comment]
后续在ppdet那边打印一下看看每个操作的flops情况，跟mmdet的get-flops.py对一下

**Comment by Senwang98** [comment]
> 在0.5x 320上基本可以对齐官方训练的结果，416上会差大概0.5个点。具体细节我也没有去对，因为主要还是想复现picodet，不过目前仍然差一点

老哥，你nanodet是用的哪个config文件对齐的，shufflenetv2_0.5_320_coco还是shufflenetv2_0.5_320_da_coco。我两张卡训完是12.8，config文件用的是带da的那个，奇奇怪怪。

**Comment by Bo396543018** [comment]
是da的，我忘记说了。我之前指的nanodet对齐是我用官方训完是12.9，我自己跑的也是12.9

**Comment by Senwang98** [comment]
@Bo396543018 
是这样，不清楚你用的是不是nanodet的release版本，因为最近nandoet在重构code，所以整体精度会低一些，我前天用nanodet-0.4.2单卡跑完是13.6。
作者当时这么回我的：
![image](https://user-images.githubusercontent.com/23122139/143168309-72ceb7c3-2026-415e-8e78-2b7fa4850d78.png)

**Comment by Bo396543018** [comment]
官方的Code复现是我同事跑的，刚问了一下，用的确实是master分支，那看起来nanodet差的还有点多。。。你现在复现到多少啦

**Comment by Senwang98** [comment]
我自己复现的，加了da之后反而降到11.9，不加da是12.4，还没有你的高。。。我用的是v2.3的mmdet2，相对版本比较旧一点

**Comment by Bo396543018** [comment]
soga，我其实这边加了da也会掉0.2个点，这可能比较偏细节了，另外一点不确定是不是存在随机性以及初始化的影响

**Comment by Senwang98** [comment]
@Bo396543018 
我把nandoet的参数改了一下之后用我的代码和你的代码加载了一下之后发现nanodet精度一摸一样（虽然很低，需要我再确认一下是不是转换错了），说明我们的实现没有分别（至于训练精度，应该是我nms阈值设为0.5导致的）。
方便问一下nandoet你们当时inference对齐精度了吗？

**Comment by Bo396543018** [comment]
这个有点早，当时没有去对齐inference，是看的FLOPS和Params

**Comment by Senwang98** [comment]
我验证了一下，nanodet提供的权重我处理过是正确的，但是mmdet2加载这个converted的权重之后精度很低

**Comment by Bo396543018** [comment]
你要不加下我的微信:bo396543018，issue成聊天区了。。
