### ISSUE TITLE
导出 onnx 模型报错 

### ISSUE THREAD

**Issue by zxx0102** [Bo396543018/Picodet_Pytorch#3]
你好，
我下载的示例模型，采用默认配置参数，导出onnx模型
```bash
python tools/deployment/pytorch2onnx.py configs/picodet/picodet_s_416_coco.py configs/picodet/picodet_s_416_coco.pth   --output-file /data/workspace/mmdet_picodet_s_416_coco.onnx
```
导出 onnx模型时报错：
```
File "/home/zxx/code/picodet_repro/mmdet/models/dense_heads/base_dense_head.py", line 427, in onnx_export
    assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
```
然后发现好像是picodet_head.py 里195 行的维度没有对齐。将代码修改如下
```python
if torch.onnx.is_in_onnx_export():
            # cls_score = (
            #     torch.sigmoid(cls_score)
            #     .reshape(1, self.num_classes, -1)
            #     .permute(0, 2, 1)
            # )
            # bbox_pred = bbox_pred.reshape(1, (self.reg_max + 1) * 4, -1).permute(
            #     0, 2, 1
            # )

            bbox_pred = bbox_pred.permute(0, 2, 3, 1).reshape(1, -1, 4 * (self.reg_max + 1))
            pred_corners = self.integral(bbox_pred)
            bbox_pred = pred_corners.reshape(1,cls_feat.shape[-2],cls_feat.shape[-1], 4).permute(0,3,1,2)

return cls_score, bbox_pred
```
但依然会报错：
```
load checkpoint from local path: configs/picodet/picodet_s_416_coco.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: bbox_head.p3_feat.scale_reg, bbox_head.p4_feat.scale_reg, bbox_head.p5_feat.scale_reg, bbox_head.p6_feat.scale_reg, bbox_head.p7_feat.scale_reg

missing keys in source state_dict: bbox_head.gfl_reg.0.weight, bbox_head.gfl_reg.0.bias, bbox_head.gfl_reg.1.weight, bbox_head.gfl_reg.1.bias, bbox_head.gfl_reg.2.weight, bbox_head.gfl_reg.2.bias, bbox_head.gfl_reg.3.weight, bbox_head.gfl_reg.3.bias
/home/zxx/code/picodet_repro/mmdet/models/dense_heads/base_dense_head.py:407: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  cfg.get('nms_pre', -1), device=device, dtype=torch.long)

...

Traceback (most recent call last):
  File "tools/deployment/pytorch2onnx.py", line 345, in <module>
    skip_postprocess=args.skip_postprocess)
  File "tools/deployment/pytorch2onnx.py", line 100, in pytorch2onnx
    dynamic_axes=dynamic_axes)
  File "/home/zxx/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/onnx/__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/zxx/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/zxx/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 701, in _export
    dynamic_axes=dynamic_axes)
  File "/home/zxx/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    _export_onnx_opset_version)
RuntimeError: number of dims don't match in permute

```
请问大佬有没有遇到这个问题，如何解决。

**Comment by Bo396543018** [comment]
嗯 这个我这几天搞android部署遇到了，因为暂时是在对齐精度，还没有更新部署相关的代码

**Comment by Bo396543018** [comment]
> 你好， 我下载的示例模型，采用默认配置参数，导出onnx模型
> 
> ```shell
> python tools/deployment/pytorch2onnx.py configs/picodet/picodet_s_416_coco.py configs/picodet/picodet_s_416_coco.pth   --output-file /data/workspace/mmdet_picodet_s_416_coco.onnx
> ```
> 
> 导出 onnx模型时报错：
> 
> ```
> File "/home/zxx/code/picodet_repro/mmdet/models/dense_heads/base_dense_head.py", line 427, in onnx_export
>     assert cls_score.size()[-2:] == bbox_pred.size()[-2:]
> ```
> 
> 然后发现好像是picodet_head.py 里195 行的维度没有对齐。将代码修改如下
> 
> ```python
> if torch.onnx.is_in_onnx_export():
>             # cls_score = (
>             #     torch.sigmoid(cls_score)
>             #     .reshape(1, self.num_classes, -1)
>             #     .permute(0, 2, 1)
>             # )
>             # bbox_pred = bbox_pred.reshape(1, (self.reg_max + 1) * 4, -1).permute(
>             #     0, 2, 1
>             # )
> 
>             bbox_pred = bbox_pred.permute(0, 2, 3, 1).reshape(1, -1, 4 * (self.reg_max + 1))
>             pred_corners = self.integral(bbox_pred)
>             bbox_pred = pred_corners.reshape(1,cls_feat.shape[-2],cls_feat.shape[-1], 4).permute(0,3,1,2)
> 
> return cls_score, bbox_pred
> ```
> 
> 但依然会报错：
> 
> ```
> load checkpoint from local path: configs/picodet/picodet_s_416_coco.pth
> The model and loaded state dict do not match exactly
> 
> unexpected key in source state_dict: bbox_head.p3_feat.scale_reg, bbox_head.p4_feat.scale_reg, bbox_head.p5_feat.scale_reg, bbox_head.p6_feat.scale_reg, bbox_head.p7_feat.scale_reg
> 
> missing keys in source state_dict: bbox_head.gfl_reg.0.weight, bbox_head.gfl_reg.0.bias, bbox_head.gfl_reg.1.weight, bbox_head.gfl_reg.1.bias, bbox_head.gfl_reg.2.weight, bbox_head.gfl_reg.2.bias, bbox_head.gfl_reg.3.weight, bbox_head.gfl_reg.3.bias
> /home/zxx/code/picodet_repro/mmdet/models/dense_heads/base_dense_head.py:407: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
>   cfg.get('nms_pre', -1), device=device, dtype=torch.long)
> 
> ...
> 
> Traceback (most recent call last):
>   File "tools/deployment/pytorch2onnx.py", line 345, in <module>
>     skip_postprocess=args.skip_postprocess)
>   File "tools/deployment/pytorch2onnx.py", line 100, in pytorch2onnx
>     dynamic_axes=dynamic_axes)
>   File "/home/zxx/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/onnx/__init__.py", line 276, in export
>     custom_opsets, enable_onnx_checker, use_external_data_format)
>   File "/home/zxx/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
>     use_external_data_format=use_external_data_format)
>   File "/home/zxx/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 701, in _export
>     dynamic_axes=dynamic_axes)
>   File "/home/zxx/miniconda3/envs/mmdet/lib/python3.7/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
>     _export_onnx_opset_version)
> RuntimeError: number of dims don't match in permute
> ```
> 
> 请问大佬有没有遇到这个问题，如何解决。

我的解决思路是参考nanodet里的export_onnx方式，因为现在实现的输出和nanodet是一致的

**Comment by Bo396543018** [comment]
我把onnx_export导出的相关代码上传了，一个是onnx_export的输出，一个是hswish。目前代码没有重构，用了很多nn里的函数

**Comment by slimwangyue** [comment]
我遇到了number of dims don't match in permute，不清楚哪里出了问题

**Comment by Bo396543018** [comment]
> 我遇到了number of dims don't match in permute，不清楚哪里出了问题

不好意思 才发现有新的消息，您这个问题解决了吗
