### ISSUE TITLE
Q: How did you pretrain the ESNet?

### ISSUE THREAD

**Issue by ranery** [Bo396543018/Picodet_Pytorch#6]
Hi,

Thank you for the great efforts!

Is there any guideline or commands for pretraining?

Best,
Haoran

**Comment by Bo396543018** [comment]
Hi, I got the pre-trained weights of ESNet by converting the paddle model weights

**Comment by ranery** [comment]
Oh, you used ppdet2mmdet.py to convert the pretrained weights, got it! Thx.
